name: Production deployment

on:
  push:
    branches:
      - main

env:
  AZURE_WEBAPP_NAME: privatechannel                   # set this to your application's name
  DOTNET_VERSION: '7.x.x'                             # set this to the dot net version to use

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    environment: production
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true


      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }} 


      - name: dotnet build and publish
        run: |
          dotnet restore
          dotnet build ./Private-Channel/PrivateChannel.Back.csproj --configuration Release
          dotnet publish ./Private-Channel/PrivateChannel.Back.csproj -c Release --property:PublishDir='./myapp' 


      - name: 'Run Azure webapp deploy'
        uses: azure/webapps-deploy@v2
        with: 
          app-name: ${{ env.AZURE_WEBAPP_NAME }} # Replace with your app name
          publish-profile: ${{ secrets.BACK_AZURE_WEBAPP_PUBLISH_PROFILE  }} # Define secret variable in repository settings as per action documentation
          package: '$./Private-Channel/myapp'


      - name: Build And Deploy PrivateChannel.Front
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.FRONT_AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "PrivateChannel.Front"
          api_location: ""
          output_location: "wwwroot"




      # Run dotnet build and publish
          
      # Deploy to Azure Web apps