name: Production deployment

on:
  push:
    branches:
      - main

env:
  AZURE_WEBAPP_NAME: privatechannel                   # set this to your application's name
  DOTNET_VERSION: '7.x.x'                             # set this to the dot net version to use

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    environment: production
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true


      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }} 


      - name: dotnet build and publish
        run: |
          dotnet restore
          dotnet build --configuration Release
          dotnet publish -c Release --property:PublishDir='./myapp' 


      - name: FTP Deploy Front
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FRONT_FTP_URL }}
          username: ${{ secrets.FRONT_FTP_USERNAME }}
          password: ${{ secrets.FRONT_FTP_PASSWORD }}
          local-dir: "./PrivateChannel.Front/myapp/wwwroot"
          server-dir: "/www/"

      - name: 'Run Azure webapp deploy'
        uses: azure/webapps-deploy@v2
        with: 
          app-name: ${{ env.AZURE_WEBAPP_NAME }} # Replace with your app name
          publish-profile: ${{ secrets.BACK_AZURE_WEBAPP_PUBLISH_PROFILE  }} # Define secret variable in repository settings as per action documentation
          package: './PrivateChannel.Back/myapp'





      # Run dotnet build and publish
          
      # Deploy to Azure Web apps